//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RajuTestMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BreedDesc
    {
        public long SNO { get; set; }
        public string AnimalName { get; set; }
        public string BreedName { get; set; }
        public string Production { get; set; }
        public string Diseases { get; set; }
        public string Feed { get; set; }
        public string Identification { get; set; }
        public string LastUpdateDate { get; set; }
        public string UpdatedBy { get; set; }
        public string LangId { get; set; }
    }
}
