//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RajuTestMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstLanguage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MstLanguage()
        {
            this.MstCropPopsTextDetails = new HashSet<MstCropPopsTextDetail>();
            this.MstCropsTextDetails = new HashSet<MstCropsTextDetail>();
            this.MstCropTypesTextDetails = new HashSet<MstCropTypesTextDetail>();
            this.MstDistrictsTextDetails = new HashSet<MstDistrictsTextDetail>();
            this.MstNewCatTextDetails = new HashSet<MstNewCatTextDetail>();
            this.MstStatesTextDetails = new HashSet<MstStatesTextDetail>();
            this.tblCropPopDescriptionTextDetails = new HashSet<tblCropPopDescriptionTextDetail>();
        }
    
        public int LangID { get; set; }
        public string LangCode { get; set; }
        public string LangName { get; set; }
        public bool IsDefault { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstCropPopsTextDetail> MstCropPopsTextDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstCropsTextDetail> MstCropsTextDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstCropTypesTextDetail> MstCropTypesTextDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstDistrictsTextDetail> MstDistrictsTextDetails { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual UserDetail UserDetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstNewCatTextDetail> MstNewCatTextDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstStatesTextDetail> MstStatesTextDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCropPopDescriptionTextDetail> tblCropPopDescriptionTextDetails { get; set; }
    }
}
