//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RajuTestMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCropPopDescription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCropPopDescription()
        {
            this.tblCropPopDescriptionTextDetails = new HashSet<tblCropPopDescriptionTextDetail>();
        }
    
        public long CropDescID { get; set; }
        public int StateID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public int CropTypeID { get; set; }
        public int CropID { get; set; }
        public int CropPopID { get; set; }
        public Nullable<int> DescriptionID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual MstCropPop MstCropPop { get; set; }
        public virtual MstCrop MstCrop { get; set; }
        public virtual MstCropType MstCropType { get; set; }
        public virtual MstDistrict MstDistrict { get; set; }
        public virtual MstState MstState { get; set; }
        public virtual tblPopDescription tblPopDescription { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual UserDetail UserDetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCropPopDescriptionTextDetail> tblCropPopDescriptionTextDetails { get; set; }
    }
}
