//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RajuTestMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserDetail()
        {
            this.MstCropPops = new HashSet<MstCropPop>();
            this.MstCropPops1 = new HashSet<MstCropPop>();
            this.MstCropPopsTextDetails = new HashSet<MstCropPopsTextDetail>();
            this.MstCropPopsTextDetails1 = new HashSet<MstCropPopsTextDetail>();
            this.MstCrops = new HashSet<MstCrop>();
            this.MstCrops1 = new HashSet<MstCrop>();
            this.MstCropsTextDetails = new HashSet<MstCropsTextDetail>();
            this.MstCropsTextDetails1 = new HashSet<MstCropsTextDetail>();
            this.MstCropTypes = new HashSet<MstCropType>();
            this.MstCropTypes1 = new HashSet<MstCropType>();
            this.MstCropTypesTextDetails = new HashSet<MstCropTypesTextDetail>();
            this.MstCropTypesTextDetails1 = new HashSet<MstCropTypesTextDetail>();
            this.MstDistricts = new HashSet<MstDistrict>();
            this.MstDistricts1 = new HashSet<MstDistrict>();
            this.MstDistrictsTextDetails = new HashSet<MstDistrictsTextDetail>();
            this.MstDistrictsTextDetails1 = new HashSet<MstDistrictsTextDetail>();
            this.MstLanguages = new HashSet<MstLanguage>();
            this.MstLanguages1 = new HashSet<MstLanguage>();
            this.MstMenus = new HashSet<MstMenu>();
            this.MstMenus1 = new HashSet<MstMenu>();
            this.MstPincodes = new HashSet<MstPincode>();
            this.MstPincodes1 = new HashSet<MstPincode>();
            this.MstStates = new HashSet<MstState>();
            this.MstStates1 = new HashSet<MstState>();
            this.MstStatesTextDetails = new HashSet<MstStatesTextDetail>();
            this.MstStatesTextDetails1 = new HashSet<MstStatesTextDetail>();
            this.MstUserRoles = new HashSet<MstUserRole>();
            this.MstUserRoles1 = new HashSet<MstUserRole>();
            this.tblCropPopDescriptions = new HashSet<tblCropPopDescription>();
            this.tblCropPopDescriptions1 = new HashSet<tblCropPopDescription>();
            this.tblCropPopDescriptionTextDetails = new HashSet<tblCropPopDescriptionTextDetail>();
            this.tblCropPopDescriptionTextDetails1 = new HashSet<tblCropPopDescriptionTextDetail>();
            this.tblDistrictCrops = new HashSet<tblDistrictCrop>();
            this.tblDistrictCrops1 = new HashSet<tblDistrictCrop>();
        }
    
        public int UserID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string DisplayName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string EmailID { get; set; }
        public string MobileNo { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstCropPop> MstCropPops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstCropPop> MstCropPops1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstCropPopsTextDetail> MstCropPopsTextDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstCropPopsTextDetail> MstCropPopsTextDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstCrop> MstCrops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstCrop> MstCrops1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstCropsTextDetail> MstCropsTextDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstCropsTextDetail> MstCropsTextDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstCropType> MstCropTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstCropType> MstCropTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstCropTypesTextDetail> MstCropTypesTextDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstCropTypesTextDetail> MstCropTypesTextDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstDistrict> MstDistricts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstDistrict> MstDistricts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstDistrictsTextDetail> MstDistrictsTextDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstDistrictsTextDetail> MstDistrictsTextDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstLanguage> MstLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstLanguage> MstLanguages1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstMenu> MstMenus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstMenu> MstMenus1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstPincode> MstPincodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstPincode> MstPincodes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstState> MstStates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstState> MstStates1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstStatesTextDetail> MstStatesTextDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstStatesTextDetail> MstStatesTextDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstUserRole> MstUserRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MstUserRole> MstUserRoles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCropPopDescription> tblCropPopDescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCropPopDescription> tblCropPopDescriptions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCropPopDescriptionTextDetail> tblCropPopDescriptionTextDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCropPopDescriptionTextDetail> tblCropPopDescriptionTextDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDistrictCrop> tblDistrictCrops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDistrictCrop> tblDistrictCrops1 { get; set; }
    }
}
