//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RajuTestMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CropPOPDescriptionDetails
    {
        public long CropDescID { get; set; }
        public int StateID { get; set; }
        public string StateName { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string DistrictName { get; set; }
        public int CropTypeID { get; set; }
        public string CropTypeName { get; set; }
        public int CropID { get; set; }
        public string CropName { get; set; }
        public int CropPopID { get; set; }
        public string CropPopName { get; set; }
        public Nullable<int> DescriptionID { get; set; }
        public string Description { get; set; }
    }
}
