//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RajuTestMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MenuDetails
    {
        public int MenuID { get; set; }
        public Nullable<int> AppID { get; set; }
        public string ApplicationName { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string ParentName { get; set; }
        public string URL { get; set; }
        public Nullable<decimal> ViewOrder { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string Role { get; set; }
    }
}
